name: Test Workflow Dispatch

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      test:
        description: "Test input"
        type: boolean
        required: false
        default: false

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 OK"
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - run: echo "Job 2 OK (après test1)"
